language: node_js
node_js:
  - 8.11.3

notifications:
  email: false
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

install:
  - yarn install

before_script:
  - yarn run prod

script:
  - yarn run test